# Generated by Django 3.0 on 2019-10-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.TextField()),
                ('message', models.TextField(max_length=300)),
                ('sender', models.EmailField(max_length=254)),
                ('cc_myself', models.BooleanField()),
            ],
        ),
    ]
